name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.10', '3.12' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: pipx install poetry
      - name: Install dependencies
        run: poetry install --with dev
      - name: Test with pytest
        run: poetry run pytest
